name: Release Python Script as EXE

on:
  push:
    tags:
      - 'v*' # Trigger workflow when a tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner to create .exe files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Use the Python version your script requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller # Install PyInstaller to create the .exe

      - name: Create EXE using PyInstaller
        run: |
          pyinstaller --onefile log_parser.py # Convert script to a single .exe file

      - name: Zip EXE and README.md
        run: |
          Compress-Archive -Path dist\log_parser.exe, README.md -DestinationPath log_parser_release.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: log_parser_release.zip
          asset_name: log_parser_release.zip
          asset_content_type: application/zip